### ISSUE TITLE
Proposal to remove royalties distribution feature

### ISSUE THREAD

**Issue by MrElement01** [LambdaAddress/LambdaAddress#20]
**Issue Description:**

As we continue to develop and refine our project, it's important for us to critically evaluate each feature's relevance and impact on our goals. One such feature is the royalty distribution mechanism. This proposal suggests that we consider removing the royalty distribution feature from Lambda Address.

**Background:**

The royalty distribution feature was conceived with the intention of incentivizing minters by offering them a share of future sales. However, recent trends in the NFT market have shown a decrease in the enforcement and recognition of these royalties, thereby diminishing the potential benefits of this feature for the minters.

**Rationale:**
Several factors contribute to the consideration of removing the royalty distribution feature:

1. **Market Trends:** As mentioned earlier, many prominent NFT exchanges have stopped enforcing and tracking royalty payments. This trend diminishes the potential value of minters' contributions and reduces the impact of this feature on our project's success.

2. **Resource Allocation:** Developing, maintaining, and ensuring the proper functioning of the royalty distribution mechanism requires valuable time and resources. By removing this feature, we can reallocate these resources to other areas that may have a more significant impact on the project's growth and user experience.

3. **Simplicity and Usability:** Streamlining our project's features can contribute to a simpler and more user-friendly experience for users. Removing the royalty distribution feature would eliminate potential complexities and uncertainties related to tracking and enforcing royalties.

**Proposal:**
In light of the aforementioned factors, I propose the removal of the royalty distribution feature from Lambda Address. This decision aligns with current market trends and allows us to focus our efforts on features that can have a more immediate and substantial impact on our project's success.

**Comment by trinidadAlpha** [comment]
Yeah let's focus on more important features.

**Comment by MrElement01** [comment]
Approved
